import Foundation
import FoundationModels

/// A structured summary of one meeting, generated by the on-device model.
@Generable(description: "A structured summary of one meeting.")
public struct MeetingSummary: Sendable {
    @Guide(
        description:
            "One sentence, in the meeting's dominant language, capturing the meeting's outcome")
    public var headline: String
    @Guide(description: "The notable points discussed, in the meeting's dominant language")
    public var keyPoints: [String]
    @Guide(description: "Decisions the meeting reached, in the meeting's dominant language")
    public var decisions: [String]
    @Guide(description: "Concrete follow-up actions agreed on, in the meeting's dominant language")
    public var actionItems: [ActionItem]
}

/// One follow-up action from a meeting.
@Generable(description: "One follow-up action from a meeting.")
public struct ActionItem: Sendable {
    @Guide(description: "Who owns this action, by name")
    public var owner: String
    @Guide(description: "What they agreed to do")
    public var what: String
    @Guide(description: "Any deadline mentioned, e.g. \"Friday\" — omitted if none was mentioned")
    public var due: String?
}

extension MeetingSummary {
    /// Renders to the markdown ``TranscriptCodec`` treats as body preamble. No "## Summary"
    /// heading — ``MeetingView``'s summary card already draws that label itself; a heading here
    /// would duplicate it. Each section is omitted if its content is empty, the same
    /// "no dangling heading" rule ``TranscriptCodec/join`` already follows for "## Transcript".
    ///
    /// Also reused as the *input* text for ``FoundationModelsSummarizer``'s reduce step, so a
    /// chunk summary's own rendering is what the model sees when merging multiple chunks — no
    /// second serialization format for the same data.
    public var markdown: String {
        var blocks: [String] = []
        if !headline.isEmpty {
            blocks.append("**\(headline)**")
        }
        if !keyPoints.isEmpty {
            blocks.append(
                (["### Key points"] + keyPoints.map { "- \($0)" }).joined(separator: "\n"))
        }
        if !decisions.isEmpty {
            blocks.append((["### Decisions"] + decisions.map { "- \($0)" }).joined(separator: "\n"))
        }
        if !actionItems.isEmpty {
            let lines = actionItems.map { item -> String in
                let due = item.due.map { " (due \($0))" } ?? ""
                return "- \(item.owner): \(item.what)\(due)"
            }
            blocks.append((["### Actions"] + lines).joined(separator: "\n"))
        }
        return blocks.joined(separator: "\n\n")
    }
}

/// Summarizes a meeting's transcript using Apple's on-device `FoundationModels`, map-reduce over
/// fixed-size chunks so a long meeting never exceeds one session's context budget.
public final class FoundationModelsSummarizer: MeetingSummarizer, Sendable {
    // No stored state — a session is created fresh per call, see `summarizeChunk` — so this is
    // safely `Sendable` outright.

    /// Chosen against the model's confirmed 4,096-token/session budget: reserving headroom for
    /// instructions, the `@Generable` schema, and generated output, a chunk excerpt should stay
    /// well under ~2,000 tokens (~7,000-8,000 characters). A short utterance-level segment runs
    /// roughly 25-120 characters, so 50 segments lands around 1,250-6,000 characters — inside
    /// budget with margin. A heuristic starting point, not a measured number; the halving-retry
    /// below is the actual safety net, not this constant.
    private static let defaultWindowSize = 50
    /// Floor below which a persistent overflow is given up on rather than chased forever.
    private static let minWindowSize = 5

    public init() {}

    public func summarize(
        _ segments: [TranscriptSegment], language: String, displayNames: [EntityID: String]
    ) async throws -> MeetingSummary {
        try await mapReduce(
            segments, language: language, displayNames: displayNames,
            windowSize: Self.defaultWindowSize)
    }

    private func mapReduce(
        _ segments: [TranscriptSegment], language: String, displayNames: [EntityID: String],
        windowSize: Int
    ) async throws -> MeetingSummary {
        let chunks = TranscriptChunker.chunk(segments, windowSize: windowSize)
        guard let first = chunks.first else {
            return MeetingSummary(headline: "", keyPoints: [], decisions: [], actionItems: [])
        }
        do {
            var chunkSummaries = [
                try await summarizeChunk(first, language: language, displayNames: displayNames)
            ]
            for chunk in chunks.dropFirst() {
                chunkSummaries.append(
                    try await summarizeChunk(chunk, language: language, displayNames: displayNames))
            }
            return chunkSummaries.count == 1
                ? chunkSummaries[0]
                : try await reduce(chunkSummaries, language: language)
        } catch LanguageModelSession.GenerationError.exceededContextWindowSize(_)
            where windowSize > Self.minWindowSize
        {
            // ponytail: halving only helps when one map call's excerpt was too large; a reduce-
            // stage overflow (many chunks, long combined input) isn't fixed by a smaller window.
            // Upgrade path if that shows up in practice: cap how many chunk summaries reduce()
            // combines per call and reduce in a tree instead of one flat pass.
            return try await mapReduce(
                segments, language: language, displayNames: displayNames,
                windowSize: windowSize / 2)
        }
    }

    private func summarizeChunk(
        _ segments: [TranscriptSegment], language: String, displayNames: [EntityID: String]
    ) async throws -> MeetingSummary {
        // Fresh session per call, per Apple's own guidance for single-turn interactions —
        // reusing one session across chunks would accumulate context and burn the same
        // token budget faster, working against the reason chunking exists.
        let session = LanguageModelSession(
            instructions:
                "You summarize one excerpt of a meeting transcript. Respond in \(language)."
        )
        let transcriptText = segments.map { segment in
            Self.line(for: segment, displayNames: displayNames)
        }.joined(separator: "\n")
        let response = try await session.respond(
            to: "Summarize this meeting transcript excerpt:\n\n\(transcriptText)",
            generating: MeetingSummary.self)
        return response.content
    }

    /// `(00:15) text` when diarization was off (or this meeting predates it); `(00:15) Marie
    /// Dupont: text` once a slot is confirmed against a person; `(00:15) Speaker 2: text` for a
    /// diarized slot nobody has confirmed yet — better attribution for the model's key-points/
    /// decisions/action-item generation than a flat, speakerless transcript.
    static func line(for segment: TranscriptSegment, displayNames: [EntityID: String])
        -> String
    {
        let timestamp = TranscriptCodec.formatTimestamp(seconds: segment.offsetSeconds)
        guard let speaker = segment.speaker else {
            return "(\(timestamp)) \(segment.text)"
        }
        let name =
            speaker.personID.flatMap { displayNames[$0] } ?? "Speaker \(speaker.slot + 1)"
        return "(\(timestamp)) \(name): \(segment.text)"
    }

    private func reduce(
        _ chunkSummaries: [MeetingSummary], language: String
    ) async throws -> MeetingSummary {
        let session = LanguageModelSession(
            instructions:
                "You merge several partial summaries of one continuous meeting into a single overall summary, deduplicating repeated points. Respond in \(language)."
        )
        let combined = chunkSummaries.enumerated()
            .map { "Part \($0.offset + 1):\n\($0.element.markdown)" }
            .joined(separator: "\n\n")
        let response = try await session.respond(
            to: "Combine these partial meeting summaries into one:\n\n\(combined)",
            generating: MeetingSummary.self)
        return response.content
    }
}
